# =====================================================================
# The "CUDA" Image (Not the default)
# -> Target this stage for development on a host machine with an
#    NVIDIA GPU and the required drivers installed.
# -> Build with: `docker build --target cuda -t muppet/muppet:cuda .`
# =====================================================================
FROM nvidia/cuda:12.8.0-cudnn-devel-ubuntu24.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update --fix-missing \
    &&   apt-get install -y  \
    unzip \
    wget \
    libgtk2.0-dev \
    bzip2 \
    ca-certificates \
    curl \
    git \
    vim \
    g++ \
    gcc \
    graphviz \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libglib2.0-0 \
    xvfb \
    libgdal-dev \
    libhdf5-dev \
    openmpi-bin \
    software-properties-common \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Download the latest installer
ADD https://astral.sh/uv/0.9.30/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

# Install the project into `/app`
WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project

# Then, add the rest of the project source code and install it
# Installing separately from its dependencies allows optimal layer caching
COPY . /app
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"
